services:
  - id: kf-api
    name: kf-api
    path: ../std-api
    buildScript: |
      git pull 
      make build-image
    deployScript: |
      docker compose stop && docker compose rm -f && docker compose up -d
  - id: kf-manager-dist
    name: kf-manager-dist
    path: /www/kf-manager-dist
    buildScript: |
      set -ex
      currentPath=$(pwd)
      rm -rf /tmp/kf-manager
      cd /tmp/kf-manager
      wget -o dist.tar.gz $ASSET_URL
      tar -zxvf dist.tar.gz
      rm -rf $currentPath
      mkdir -p $currentPath
      mv dist/* $currentPath
    deployScript: |
      set -ex
      git pull
      echo 'already deployed'