services:
  - id: kf-api
    name: kf-api
    path: ../std-api
    buildScript: |
      git pull 
      make build-image
    deployScript: |
      docker compose stop && docker compose rm -f && docker compose up -d
  - id: kf-manager-dist
    name: kf-manager-dist
    path: /www/kf-manager-dist
    buildScript: |
      set -ex
      git pull
    deployScript: |
      set -ex
      git pull
      echo 'already deployed'