POST http://localhost:8083/githook
Content-Type: application/json

{
  "ref": "refs/heads/main",
  "before": "713ac02b250b9fbf846083046cc33a68bcc206af",
  "after": "1080d55e983a9644113fd36cd4186ce33c4a7488",
  "repository": {
    "id": 906973031,
    "node_id": "R_kgDONg9PZw",
    "name": "kf-manager-dist",
    "full_name": "smart-kf/kf-manager-dist",
    "private": false,
    "owner": {
      "name": "smart-kf",
      "email": null,
      "login": "smart-kf",
      "id": 191563369,
      "node_id": "O_kgDOC2sGaQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/191563369?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/smart-kf",
      "html_url": "https://github.com/smart-kf",
      "followers_url": "https://api.github.com/users/smart-kf/followers",
      "following_url": "https://api.github.com/users/smart-kf/following{/other_user}",
      "gists_url": "https://api.github.com/users/smart-kf/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/smart-kf/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/smart-kf/subscriptions",
      "organizations_url": "https://api.github.com/users/smart-kf/orgs",
      "repos_url": "https://api.github.com/users/smart-kf/repos",
      "events_url": "https://api.github.com/users/smart-kf/events{/privacy}",
      "received_events_url": "https://api.github.com/users/smart-kf/received_events",
      "type": "Organization",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/smart-kf/kf-manager-dist",
    "description": null,
    "fork": false,
    "url": "https://github.com/smart-kf/kf-manager-dist",
    "forks_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/forks",
    "keys_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/teams",
    "hooks_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/hooks",
    "issue_events_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/issues/events{/number}",
    "events_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/events",
    "assignees_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/assignees{/user}",
    "branches_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/branches{/branch}",
    "tags_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/tags",
    "blobs_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/languages",
    "stargazers_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/stargazers",
    "contributors_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/contributors",
    "subscribers_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/subscribers",
    "subscription_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/subscription",
    "commits_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/contents/{+path}",
    "compare_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/merges",
    "archive_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/downloads",
    "issues_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/issues{/number}",
    "pulls_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/labels{/name}",
    "releases_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/releases{/id}",
    "deployments_url": "https://api.github.com/repos/smart-kf/kf-manager-dist/deployments",
    "created_at": 1734873201,
    "updated_at": "2024-12-22T13:27:24Z",
    "pushed_at": 1734874591,
    "git_url": "git://github.com/smart-kf/kf-manager-dist.git",
    "ssh_url": "git@github.com:smart-kf/kf-manager-dist.git",
    "clone_url": "https://github.com/smart-kf/kf-manager-dist.git",
    "svn_url": "https://github.com/smart-kf/kf-manager-dist",
    "homepage": null,
    "size": 0,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "HTML",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main",
    "stargazers": 0,
    "master_branch": "main",
    "organization": "smart-kf",
    "custom_properties": {

    }
  },
  "pusher": {
    "name": "clearcodecn",
    "email": "34591322+clearcodecn@users.noreply.github.com"
  },
  "organization": {
    "login": "smart-kf",
    "id": 191563369,
    "node_id": "O_kgDOC2sGaQ",
    "url": "https://api.github.com/orgs/smart-kf",
    "repos_url": "https://api.github.com/orgs/smart-kf/repos",
    "events_url": "https://api.github.com/orgs/smart-kf/events",
    "hooks_url": "https://api.github.com/orgs/smart-kf/hooks",
    "issues_url": "https://api.github.com/orgs/smart-kf/issues",
    "members_url": "https://api.github.com/orgs/smart-kf/members{/member}",
    "public_members_url": "https://api.github.com/orgs/smart-kf/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/191563369?v=4",
    "description": null
  },
  "sender": {
    "login": "clearcodecn",
    "id": 34591322,
    "node_id": "MDQ6VXNlcjM0NTkxMzIy",
    "avatar_url": "https://avatars.githubusercontent.com/u/34591322?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/clearcodecn",
    "html_url": "https://github.com/clearcodecn",
    "followers_url": "https://api.github.com/users/clearcodecn/followers",
    "following_url": "https://api.github.com/users/clearcodecn/following{/other_user}",
    "gists_url": "https://api.github.com/users/clearcodecn/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/clearcodecn/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/clearcodecn/subscriptions",
    "organizations_url": "https://api.github.com/users/clearcodecn/orgs",
    "repos_url": "https://api.github.com/users/clearcodecn/repos",
    "events_url": "https://api.github.com/users/clearcodecn/events{/privacy}",
    "received_events_url": "https://api.github.com/users/clearcodecn/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false
  },
  "created": false,
  "deleted": false,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.com/smart-kf/kf-manager-dist/compare/713ac02b250b...1080d55e983a",
  "commits": [
    {
      "id": "1080d55e983a9644113fd36cd4186ce33c4a7488",
      "tree_id": "4e15f1a2b8e594d46629f84310a3151045018672",
      "distinct": true,
      "message": "feat: hook",
      "timestamp": "2024-12-22T21:36:26+08:00",
      "url": "https://github.com/smart-kf/kf-manager-dist/commit/1080d55e983a9644113fd36cd4186ce33c4a7488",
      "author": {
        "name": "zhangmj",
        "email": "zhangmj1@dustess.com"
      },
      "committer": {
        "name": "zhangmj",
        "email": "zhangmj1@dustess.com"
      },
      "added": [

      ],
      "removed": [

      ],
      "modified": [
        "index.html"
      ]
    }
  ],
  "head_commit": {
    "id": "1080d55e983a9644113fd36cd4186ce33c4a7488",
    "tree_id": "4e15f1a2b8e594d46629f84310a3151045018672",
    "distinct": true,
    "message": "feat: hook",
    "timestamp": "2024-12-22T21:36:26+08:00",
    "url": "https://github.com/smart-kf/kf-manager-dist/commit/1080d55e983a9644113fd36cd4186ce33c4a7488",
    "author": {
      "name": "zhangmj",
      "email": "zhangmj1@dustess.com"
    },
    "committer": {
      "name": "zhangmj",
      "email": "zhangmj1@dustess.com"
    },
    "added": [

    ],
    "removed": [

    ],
    "modified": [
      "index.html"
    ]
  }
}