services:
  - id: kf-api
    name: smart-kf/kf-api
    path: /www/kf-api
    buildScript: |
      USERNAME="smart-kf"
      REPO="kf-api"
      LATEST_RELEASE=$(curl -s "https://api.github.com/repos/$USERNAME/$REPO/releases/latest" | grep "tag_name" | sed -E 's/.*"([^"]+)".*/\1/')
      wget https://github.com/smart-kf/kf-manager/releases/download/$LATEST_RELEASE/app.tar.gz
      tar -zxvf dist.tar.gz 
      rm -rf bin
      mv app bin/
      make build-image
    deployScript: |
      docker compose stop && docker compose rm -f && docker compose up -d
  - id: kf-manager-dist
    name: smart-kf/kf-manager
    path: /www/kf-manager-dist
    buildScript: |
      set -ex
      rm -rf ./*
      USERNAME="smart-kf"
      REPO="kf-manager"
      # 获取最新release的信息
      LATEST_RELEASE=$(curl -s "https://api.github.com/repos/$USERNAME/$REPO/releases/latest" | grep "tag_name" | sed -E 's/.*"([^"]+)".*/\1/')
      wget https://github.com/smart-kf/kf-manager/releases/download/$LATEST_RELEASE/dist.tar.gz
      tar -zxvf dist.tar.gz 
      mv dist/* .
      rm -rf dist dist.tar.gz
    deployScript: |
      set -ex
      git pull
      echo 'already deployed'