services:
  - id: kf-api
    name: kf-api
    path: /www/kf-api
    buildScript: |
      git pull 
      make build-image
    deployScript: |
      docker compose stop && docker compose rm -f && docker compose up -d